-- 1 up

CREATE TABLE item(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	genesis TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	modified TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	name TEXT NOT NULL,
	type INTEGER NOT NULL,
	amount REAL NOT NULL DEFAULT 0,
	location INTEGER,
	active BOOLEAN NOT NULL CHECK (active IN (0,1)) DEFAULT 1,
	FOREIGN KEY(type) REFERENCES item_type(id),
	FOREIGN KEY(location) REFERENCES location(id)
);

-- 1 down

DROP TABLE item;