-- 1 up

CREATE TABLE location(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	genesis TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	modified TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	name TEXT NOT NULL,
	description TEXT,
	active BOOLEAN NOT NULL CHECK (active IN (0,1))
);

-- 1 down

DROP TABLE location;